# fish completion for jobwrap
complete -c jobwrap -f -n '__fish_use_subcommand' -a list -d 'List registered jobs'
complete -c jobwrap -f -n '__fish_use_subcommand' -a show -d 'Show job details'
complete -c jobwrap -f -n '__fish_use_subcommand' -a logs -d 'Print a job output log'
complete -c jobwrap -f -n '__fish_use_subcommand' -a signal -d 'Send a named signal'
complete -c jobwrap -f -n '__fish_use_subcommand' -a stop -d 'Send SIGTERM'
complete -c jobwrap -f -n '__fish_use_subcommand' -a open -d 'Open the web interface'
complete -c jobwrap -f -n '__fish_use_subcommand' -a daemon -d 'Manage the daemon'
complete -c jobwrap -f -n '__fish_use_subcommand' -a config -d 'Manage configuration'
complete -c jobwrap -f -n '__fish_use_subcommand' -a auth -d 'Manage password authentication'
complete -c jobwrap -f -n '__fish_use_subcommand' -a token -d 'Manage API tokens'

complete -c jobwrap -s n -l name -d 'Job name'
complete -c jobwrap -l profile -d 'Access profile'
complete -c jobwrap -l detach -d 'Detach from the terminal'
complete -c jobwrap -l no-web -d 'Do not use the web server'
complete -c jobwrap -l no-record -d 'Do not record output'

complete -c jobwrap -n '__fish_seen_subcommand_from signal' -a 'int term hup quit stop cont kill'
complete -c jobwrap -n '__fish_seen_subcommand_from daemon' -a 'status start stop'
complete -c jobwrap -n '__fish_seen_subcommand_from config' -a 'path init validate effective explain'
complete -c jobwrap -n '__fish_seen_subcommand_from auth' -a 'set-password remove-password status'
complete -c jobwrap -n '__fish_seen_subcommand_from token' -a 'create list revoke'
